spin_manifest_version = 2

[application]
authors = ["Rui Lopes <rgl@ruilopes.com>"]
description = "Example Spin HTTP Application written in TypeScript"
name = "spin-http-ts-example"
version = "0.4.0"

[[trigger.http]]
route = "/..."
component = "spin-http-ts-example"

[component.spin-http-ts-example]
source = "target/spin-http-ts-example.wasm"
exclude_files = ["**/node_modules"]
[component.spin-http-ts-example.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
